### ISSUE TITLE
Integrate Starknet Foundry as Testing Framework

### ISSUE THREAD

**Issue by cloudvenger** [carbonable-labs/carbon-protocol-v3#13]
**Description**
---
Integrate [Starknet Foundry](https://github.com/foundry-rs/starknet-foundry) as Testing Framework

Additional Information
---------------------------
[ Medium/Low Difficulty  - Cairo - High Priority]

**Acceptance Criteria**
---

- [ ] Integrate Starknet Foundry as testing Framework
- [ ] Implement some nominal test to validated the right integration of Foundry

**Comment by JimmyFate** [comment]
Hey :)
I could try to tackle this

**Comment by tekkac** [comment]
Contribute to Carbonable during ODHack: 
Provable environmental infra

- Go to the CarbonableOD Telegram: https://t.me/carbonableOD
- Present yourself and tell us which issue you want to pick
- Explain shortly how you want to tackle the issue
- Ask a question if you need some clarity
- When you're selected you will be assigned to the issue

**Comment by 0xthomass** [comment]
Hey, I would like to work on this one. Posted a message on TG :)
