### ISSUE TITLE
Integrate ERC-4906

### ISSUE THREAD

**Issue by tekkac** [carbonable-labs/carbon-protocol-v3#19]
**Description**
---
Integrate the ERC-4906 Cairo 2.6 component [cairo-erc-4906 repo](https://github.com/Carbonable-labs/cairo-erc-4906).

**Additional Information**
---------------------------
[Medium  - Cairo - Low Priority]

**Acceptance Criteria**
---
- [ ] Add the ERC-4906 dependecy
- [ ] Add the ERC-4906 Starknet component and methods to the project contract
- [ ] Implement unit tests

**Comment by AryanGodara** [comment]
Hi @tekkac @Khyati729 
Can I work on this issue for the ODHack week?
I've started exploring the repo, and have good idea on how to implement this one :D

**Comment by tekkac** [comment]
Contribute to Carbonable during ODHack: 
Provable environmental infra

- Go to the CarbonableOD Telegram: https://t.me/carbonableOD
- Present yourself and tell us which issue you want to pick
- Explain shortly how you want to tackle the issue
- Ask a question if you need some clarity
- When you're selected you will be assigned to the issue

**Comment by manlikeHB** [comment]
Hi @tekkac @Khyati729, I would like to work on this, I left a message in the telegram group.

**Comment by julienbrs** [comment]
After discussions with @manlikeHB, I've updated the difficulty of this issue to Medium.

### Reasons why:
ERC-4906 got functions like `_emit_metadata_update` that requires a `ŧoken_id` in argument. However ERC1155 OpenZeppelin's implementation returns the same URI for *all* token types. It relies on the token type ID substitution mechanism defined in the EIP: https://eips.ethereum.org/EIPS/eip-1155#metadata.
For example, the `https://token-cdn-domain/\{id\}.json` URI would be interpreted by clients as `https://token-cdn-domain/000000000000000000000000000000000000000000000000000000000004cce0.json` for token type ID 0x4cce0.

There might be 2 solutions:
- Emit a Range Event:  emit the `BatchMetadataUpdate` event to indicate that the metadata for a range of tokens has been updated. In our case we would update ALL the tokens, even the ones that haven't changed.
- inspect the new_uri parameter in `set_uri` to extract the token_id by parsing.
