### ISSUE TITLE
[OpenZepplin] rewrite Mint function of ERC-1155 to no use "safe_mint"

### ISSUE THREAD

**Issue by cloudvenger** [carbonable-labs/carbon-protocol-v3#27]
**Description**
---
[OpenZepplin] rewrite Mint function of ERC-1155 to no use "safe_mint"

**Additional context**
---
the problem is that:
- if the receiver is not deployed: it fails
- if the receiver is a contract that does not implement IERC_1155_RECEIVER, it fails

**Comment by tekkac** [comment]
it seems this is not needed anymore for now as the contract doesn't use safe_mint.
