### ISSUE TITLE
CPv3 - Unit Testing - Mint function

### ISSUE THREAD

**Issue by Khyati729** [carbonable-labs/carbon-protocol-v3#63]
Description
-------------------------
CPv3 - Unit Testing
Functions to test:
- `get_available_money_amount`
- Create a function that can cancel the mint (change the value of `Mint_cancel`), and test it (with `is_canceled`)

Acceptance Criteria
------------------------------
- [x] Tests should pass
- [x] Scarb fmt

**Comment by axelizsak** [comment]
Hey! I take this one :)

**Comment by adrianvrj** [comment]
Hi! Can I hop on this one?
It would probably take me around 2 days to complete it.
This is how I would approach it:

1. Understand the Functions to be Tested
- get_available_money_amount: Identify what this function does. Typically, it might return the current available amount of money from a certain source.
- Mint_cancel Function: This function should change the value of Mint_cancel.
2. Set Up the Testing Environment
3. Create the Mint_cancel Function
4. Create a Test for the Mint_cancel Function
5.  Implement the is_canceled Function
6. Create a Test for the is_canceled Function
7. Test the get_available_money_amount Function
8.  Run the Tests
9. Format the Code Using Scarb fmt

**Comment by julienbrs** [comment]
Hi @adrianvrj, sorry but this issue is already picked up, but OdHack is coming soon, and thus new tickets to take :)
