### ISSUE TITLE
Implement allcontributors bot

### ISSUE THREAD

**Issue by julienbrs** [carbonable-labs/carbon-protocol-v3#67]
Low priority
- [x] init bot
- [x] add contributors

**Comment by raizo07** [comment]
@julienbrs if this issue is open, I'll like to be assigned to work on it, I'll be done in  an hour.

**Comment by julienbrs** [comment]
I'm already working on it as it requires permission about repo management

**Comment by julienbrs** [comment]
@all-contributors please add @julienbrs for code

**Comment by raizo07** [comment]
> I'm already working on it as it requires permission about repo management

That's with installing the bot, not the script.

**Comment by julienbrs** [comment]
@all-contributors please add @julienbrs for code

**Comment by julienbrs** [comment]
> > I'm already working on it as it requires permission about repo management
> 
> That's with installing the bot, not the script.

What do you mean? No script should be required if we aren't using the CI I think. It's about the config and setup

**Comment by julienbrs** [comment]
@all-contributors please add @schwepps  for code

**Comment by raizo07** [comment]
> > > I'm already working on it as it requires permission about repo management
> > 
> > 
> > That's with installing the bot, not the script.
> 
> What do you mean? No script should be required if we aren't using the CI I think. It's about the config and setup

So the code in the allcontributors src and the readme is what makes it to throw the processing error.

**Comment by julienbrs** [comment]
@raizo07 so no need to setup .all-contributorsrc as mentioned in their doc and the bot will do it by itself? reverted the setup but the bot isn't responding now #90

**Comment by raizo07** [comment]
> @raizo07 so no need to setup .all-contributorsrc as mentioned in their doc and the bot will do it by itself? reverted the setup but the bot isn't responding now #90

I just pushed a PR for you that when merged, should fix it.

**Comment by julienbrs** [comment]
> I just pushed a PR for you that when merged, should fix it.

Yes did the same, apparently the issue was because you can't call the bot in the first message of an issue or a PR

**Comment by raizo07** [comment]
> @raizo07 so no need to setup .all-contributorsrc as mentioned in their doc and the bot will do it by itself? reverted the setup but the bot isn't responding now #90

I can see it is working now, awesome. I'll close my PR now.

**Comment by julienbrs** [comment]
@all-contributors please add @raizo07 for  bug help
