### ISSUE TITLE
[DevOps] Github Action - Automatize test runner at merge

### ISSUE THREAD

**Issue by Khyati729** [carbonable-labs/carbon-protocol-v3#68]
**Description**
---
As Carbonable, we want to use Github action to launch tests during CI/CD when we merge on main.  CI should fail if all tests don't pass.

**Additional context**
---
[ Medium/Low Difficulty  - Cairo/DevOps - Medium Priority]

**Acceptance Criteria**
---
- [ ]  Implement Github Action to launch tests through a script in bash.
- [ ]  If some test fails, CI should fail and a message should explain which test crashed.
- [ ]  Config to trigger this Github action only when PR are merged in Main branch

**Comment by lindsaymb15** [comment]
Hi! @Khyati729 My name is Lindsay Morales. I'm a Software Engineer based in Costa Rica and this is my third OD hack!

I'd love to have the opportunity to tackle this issue, and be able to learn more about this project. I've implemented GitHub Actions on some work projects I have worked on. Even though I haven't implemented it on a Cairo project, I already have knowledge on how to implement this.

How? Under the `.github/workflows` directory I'd create a `main.yml` file where I'd define the desired workflow/pipeline including the conditions: only on merge on main branch and the job: test in this case, with its corresponding steps.

**Comment by Khyati729** [comment]
Contribute to Carbonable during ODHack:
Provable environmental infra

Go to the CarbonableOD Telegram: https://t.me/carbonableOD
Present yourself and tell us which issue you want to pick
Explain shortly how you want to tackle the issue
Ask a question if you need some clarity
When you're selected you will be assigned to the issue

**Comment by lindsaymoralesb** [comment]
Hi! @Khyati729 I already left a message on the tg!
My name is Lindsay Morales. I'm a Software Engineer based in Costa Rica and this is my third OD hack!

I'd love to have the opportunity to tackle this issue, and be able to learn more about this project. I've implemented GitHub Actions on some work projects I have worked on. Even though I haven't implemented it on a Cairo project, I already have knowledge on how to implement this.

How? Under the .github/workflows directory I'd create a main.yml file where I'd define the desired workflow/pipeline including the conditions: only on merge on main branch and the job: test in this case, with its corresponding steps.

**Comment by lordshashank** [comment]
Hey @Khyati729, I would like to work on this issue. I have experience with implementing github actions, would love to do it here.
- I would configure ci.yml to setup the `scarf` and `starknet-foundry` 
- All the tests in `texts/` would be run.
- A github summary would be created to better view the test results.
- This ci workflow would be run on every pr being merged on main.

**Comment by lindsaymoralesb** [comment]
Hi! @Khyati729 [PR](https://github.com/carbonable-labs/carbon-protocol-v3/pull/81) is ready for review. I included some screenshots of the output (fail and success), please let me know if that aligns to that you were expecting or if there's any feedback for me.
