### ISSUE TITLE
Unit Tests getters minter money functions

### ISSUE THREAD

**Issue by Khyati729** [carbonable-labs/carbon-protocol-v3#69]
**Description**
---
In Carbon Protocol v3 - implement tests to verify the results of the following functions:

- get_available_money_amount
- get_max_money_amount
- get_min_money_amount_per_tx
- is_sold_out
- set_min_money_amount_per_tx

Also test tricky scenarios and specific edge cases for each function.

**Additional context**
---
[ Low Difficulty  - Cairo/DevOps - Low Priority]

**Suggested Evolution**
---
A clear and concise summary of the evolution, changing behavior that should be made

**Acceptance Criteria**
---
- [ ]  Tests should pass
- [ ]  Follow Contribution guidelines and ask for help if needed in the CarbonableOD Telegram: https://t.me/carbonableOD

**Comment by silent-cipher** [comment]
@Khyati729, Can I take this issue?

**Comment by NueloSE** [comment]
@Khyati729 I am a web 3 developer with experience in unit testing and integration testing. Can i contribute to this issue?

**Comment by Khyati729** [comment]
Contribute to Carbonable during ODHack: 
Provable environmental infra

- Go to the CarbonableOD Telegram: https://t.me/carbonableOD
- Present yourself and tell us which issue you want to pick
- Explain shortly how you want to tackle the issue
- Ask a question if you need some clarity
- When you're selected you will be assigned to the issue

**Comment by adrianvrj** [comment]
Hi! I just sent a message on TG!

Hi, my name is Adrian Vargas, a beginner in this web 3 world looking for opportunities to grow and learn as much as I can

I want to pick this issue:

https://github.com/carbonable-labs/carbon-protocol-v3/issues/69

Here is how I would approach it:

- Initialize the Project and study the code and specific functions to be tested 
- Install required dependencies and necessary environment for development 
- Create a test file and import necessary modules for the tests
- Write tests for all given functions and run the tests making sure everything works fine
- Check out and study different tricky and edge cases and run tests for them too

**Comment by adrianvrj** [comment]
Hi @Khyati729 I think I am too busy for this issue, I got a friend that's been helping me and understands quite good what he has to do @EmmanuelAr

**Comment by EmmanuelAR** [comment]
Yes I was talking to @adrianvrj and I can work on this! Let me know @adrianvrj
