### ISSUE TITLE
Unit Tests getters minter prices & address

### ISSUE THREAD

**Issue by Khyati729** [carbonable-labs/carbon-protocol-v3#70]
**Description**
---
In Carbon Protocol v3 - implement units tests to verify the results of the following functions:

- get_carbonable_project_address
- get_payment_token_address
- set_unit_price
- get_unit_price

**Additional context**
---
[ Low Difficulty  - Cairo/DevOps - Low Priority]

**Acceptance Criteria**
---
- [ ]  Tests should pass
- [ ]  Follow Contribution guidelines and ask for help if needed in the CarbonableOD Telegram: https://t.me/carbonableOD

**Comment by shivam6862** [comment]
@Khyati729  Hi, i can work on this. i am a developer with a three of years of experience. i will complete in 3 working days



I want to work on this [issue](https://github.com/carbonable-labs/carbon-protocol-v3/issues/70)


I will tackle the issue in this manner 

- Fork the repo and understand the codebase 
- Setup the environment to run it locally
- Write the a strong test for it  and test it

**Comment by jsandinoDev** [comment]
Hello, I would like to work on it :)

**Comment by Khyati729** [comment]
Contribute to Carbonable during ODHack: 
Provable environmental infra

- Go to the CarbonableOD Telegram: https://t.me/carbonableOD
- Present yourself and tell us which issue you want to pick
- Explain shortly how you want to tackle the issue
- Ask a question if you need some clarity
- When you're selected you will be assigned to the issue
