### ISSUE TITLE
Unit Tests functions project.cairo

### ISSUE THREAD

**Issue by Khyati729** [carbonable-labs/carbon-protocol-v3#71]
**Description**
---
In Carbon Protocol v3 - implement tests to verify the results of the functions not tested yet:

- set_uri
- decimals
- shares_of
- is_approved_for_all
- set_approval_for_all
- offset

**Additional context**
---
[ Medium Difficulty  - Cairo/DevOps - Low Priority]

**Acceptance Criteria**
---
- [ ]  Tests should pass
- [ ]  Follow Contribution guidelines and ask for help if needed in the CarbonableOD Telegram: https://t.me/carbonableOD

**Comment by EmmanuelAR** [comment]
Hey @Khyati729 can i work on this? I will take reference of old test in the project, also i check the functions and seems to dont have to much code, so will be fast, let me know!

**Comment by Khyati729** [comment]
Contribute to Carbonable during ODHack: 
Provable environmental infra

- Go to the CarbonableOD Telegram: https://t.me/carbonableOD
- Present yourself and tell us which issue you want to pick
- Explain shortly how you want to tackle the issue
- Ask a question if you need some clarity
- When you're selected you will be assigned to the issue

**Comment by BenFaruna** [comment]
Hello @Khyati729 my name is Benjamin Faruna.
Can I take up this issue?
I already introduced myself on the carbonable sc channel on telegram.

**Comment by Shoetan** [comment]
Hi @Khyati729  can i take this up 

I will first fork the repo
clone forked repo to my local machine
Set up project locally with all dependencies like scarb.
Explore project and understand the functions.
Import necessary modules from starknets core lib for tests or from internal modules.
Create test files either external test files or right inside the contract file as the case maybe after studing the existing project and finding patterns
Make sure all test past. 
look out for any surprises that might spring up

**Comment by Khyati729** [comment]
@EmmanuelAR  @BenFaruna apologies but you need to do both the introductions.
@BenFaruna I didnt see any introductions from you side, could you please confirm which group you did that on
 CarbonableOD Telegram: https://t.me/carbonableOD 
Kindly please go ahead and chose from the other issues we have still open.

**Comment by BenFaruna** [comment]
I just sent a message on telegram @Khyati729
