### ISSUE TITLE
Minter of ERC721

### ISSUE THREAD

**Issue by Khyati729** [carbonable-labs/carbon-protocol-v3#72]
**Description**
---
In Carbon Protocol v3 - When the user calls the mint function (to mint ERC1155, in project.cairo) for the first time, it should also mint an ERC721. For the moment, we don’t mind what ERC721 it is and the details about it.

**User Flow**
----
User buy with the public_buy function ⇒ call of  fn mint in project.cairo ⇒ mint of a dedicated ERC721 with mint function of that ERC721.cairo ⇒ then mint of the regular erc1155.

**Additional context**
---
[ Medium Difficulty  - Cairo - High Priority]

**Acceptance Criteria**
---
- [ ]  Create ERC721 contract with dummy details. Only the contract project.cairo should be allowed to call mint function from that ERC721 contract.
- [ ]  add the call to mint 1 NFT of that new contract when we call `mint` from project.cairo
- [ ]  If the user already minted an NFT from that dummy ERC721 contract, don’t mint an other one and just mint ERC1155.
- [ ]  Follow Contribution guidelines and ask for help if needed in the CarbonableOD Telegram: https://t.me/carbonableOD

**Comment by jsandinoDev** [comment]
Hello @Khyati729 , I would like to work on it :)

**Comment by jsandinoDev** [comment]
Hi @Khyati729, I would like to work on it :)

**Comment by danielcdz** [comment]
Hello @Khyati729 !
My name is Daniel Calderon, I'm a software developer and OD contributor from Costa Rica, and this is my third ODHack, I would love to help with this issue during the current one, also I already joined the TG group.
I will tackle this issue by:

- Creating a simple ERC721.cairo contract with a mint function, on this function, I will verify that the contract calling the method should be `project.cairo`, also I will validate that an address or user can't mint more than one ER721 token/nft. 
-  I will add this call to the mint function in `project.cairo`,  the call of this function will mint an NFT only if it is the first time

**Comment by Khyati729** [comment]
Contribute to Carbonable during ODHack: 
Provable environmental infra

- Go to the CarbonableOD Telegram: https://t.me/carbonableOD
- Present yourself and tell us which issue you want to pick
- Explain shortly how you want to tackle the issue
- Ask a question if you need some clarity
- When you're selected you will be assigned to the issue

**Comment by od-hunter** [comment]
Hello @Khyati729 , can I be assigned this issue please? I’m ready to start work. I already commented in the telegram group as od-hunter. Thank you.

**Comment by od-hunter** [comment]
Hello @Khyati729 , so sorry for the delay, I’ll send a draft pr before the end of , thank you.🙏🏾
