### ISSUE TITLE
Implement URI to deploy on testnet

### ISSUE THREAD

**Issue by julienbrs** [carbonable-labs/carbon-protocol-v3#76]
**Acceptance criteria**
---
- [ ] Contract recognized as 1155
- [ ] Nfts minted displayed correctly
- [ ] Should work both on Starkscan & Voyager

**Comment by Iwueseiter** [comment]
@julienbrs Can I work on this?

**Comment by julienbrs** [comment]
It's an internal issue that I'm working on, sorry

**Comment by julienbrs** [comment]
New Metadata management with SVG on-chain will be merged.
